name: Test Build Deploy (Backend)
on:
  pull_request:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: backend
jobs:
  build-test:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout of repository
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: yarn
        cache-dependency-path: backend/yarn.lock

    - name: Install dependencies
      run: yarn --prefer-offline

    - name: Test
      run: yarn test
