name: Test Build Deploy (Frontend)
on:
  pull_request:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: frontend
jobs:
  install-build:
    name: Install dependencies and build app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout of repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: yarn
          cache-dependency-path: frontend/yarn.lock

      - name: Install dependencies
        # Tell yarn to use cached downloads whenever possible instead of downloading from the server
        run: yarn --prefer-offline

      - name: Build
        run: yarn build

  lint-test:
    name: Lint and Run unit tests
    runs-on: ubuntu-latest
    needs: install-build
    steps:
      - name: Checkout of repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: yarn
          cache-dependency-path: frontend/yarn.lock

      - name: Lint package
        run: yarn lint

      - name: Run tests
        run: yarn test

  interaction-and-accessibility:
    name: Interaction and Accessibility
    runs-on: ubuntu-latest
    needs: install-build
    steps:
      - name: Checkout of repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: yarn
          cache-dependency-path: frontend/yarn.lock

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Build Storybook
        run: yarn build-storybook --quiet

      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:6006 && yarn test-storybook"
